on: [push]
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl http://ip.tool.chinaz.com|grep 'name="ip" url="true"'
      - run: git config --global --list
